export type {
  ActiveTurnData,
  AgentTaskData,
  AgentTaskMessageData,
  AgentThreadData,
  AgentTreeData,
  AttachmentData,
  AgentPlanData,
  CapabilityDescriptor,
  CapabilityKind,
  ConnectorStatusData,
  ConversationAccessMode,
  ConversationActivityData,
  ConversationDisplayMessageData,
  ConversationMessageData,
  ConversationProgressData,
  JsonRpcId,
  JsonRpcNotification,
  JsonRpcOutgoing,
  JsonRpcRequest,
  JsonRpcResponse,
  MessageCapabilityData,
  ProcessSnapshotData,
  QueuedTurnData,
  FollowUpDelivery,
  SuggestionLanguage,
  ThreadlightNotificationMap,
  ThreadlightNotificationMethod,
  ThreadlightMethod,
  TokenUsageData,
  TurnDiagnosticsData,
  TurnMode,
} from "@threadlight/protocol";

import type { JsonRpcOutgoing } from "@threadlight/protocol";

export type SendMessage = (message: JsonRpcOutgoing) => void;
